#############################################################################
# Makefile for building: Babel
# Generated by qmake (2.01a) (Qt 4.8.6) on: jeu. oct. 30 18:16:58 2014
# Project:  Babel.pro
# Template: app
# Command: /usr/lib/i386-linux-gnu/qt4/bin/qmake -o Makefile Babel.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I. -IIncludes -ITest/DesignPatterns -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -ldl -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/i386-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Client/Client.cpp \
		Client/main.cpp \
		Gui/Factory.cpp \
		Gui/Home.cpp \
		Gui/Inscription.cpp \
		Parser/XMLParser.cpp \
		Modules/DllLoader/UnixDllLoadder.cpp moc_Inscription.cpp
OBJECTS       = Client.o \
		main.o \
		Factory.o \
		Home.o \
		Inscription.o \
		XMLParser.o \
		UnixDllLoadder.o \
		moc_Inscription.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Babel.pro
QMAKE_TARGET  = Babel
DESTDIR       = 
TARGET        = Babel

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_inscription.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Babel.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtXml.prl \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Babel.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtXml.prl:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Babel.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Babel1.0.0 || $(MKDIR) .tmp/Babel1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Babel1.0.0/ && $(COPY_FILE) --parents Includes/BabelDataDecoder.h Includes/BabelDataEncoder.h Includes/BabelSound.h Includes/Client.h Includes/Connexion.h Includes/Factory.h Includes/Home.h Includes/IBabelData.h Includes/IBabelSound.h Includes/IDllLoader.h Includes/IGui.h Includes/IModule.h Includes/Inscription.h Includes/Lexer.h Includes/OpenCV.h Includes/Subscribe.h Includes/UnixDllLoader.h Includes/UserInfo.h Includes/View.h Includes/WinDllLoader.h Includes/XMLParser.h .tmp/Babel1.0.0/ && $(COPY_FILE) --parents Client/Client.cpp Client/main.cpp Gui/Factory.cpp Gui/Home.cpp Gui/Inscription.cpp Parser/XMLParser.cpp Modules/DllLoader/UnixDllLoadder.cpp .tmp/Babel1.0.0/ && $(COPY_FILE) --parents Gui/Ui/inscription.ui .tmp/Babel1.0.0/ && (cd `dirname .tmp/Babel1.0.0` && $(TAR) Babel1.0.0.tar Babel1.0.0 && $(COMPRESS) Babel1.0.0.tar) && $(MOVE) `dirname .tmp/Babel1.0.0`/Babel1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Babel1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_Inscription.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Inscription.cpp
moc_Inscription.cpp: Includes/Inscription.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) Includes/Inscription.h -o moc_Inscription.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_inscription.h
compiler_uic_clean:
	-$(DEL_FILE) ui_inscription.h
ui_inscription.h: Gui/Ui/inscription.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic Gui/Ui/inscription.ui -o ui_inscription.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

Client.o: Client/Client.cpp Includes/Client.h \
		Includes/Lexer.h \
		Includes/XMLParser.h \
		Includes/IDllLoader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Client.o Client/Client.cpp

main.o: Client/main.cpp Includes/Client.h \
		Includes/Lexer.h \
		Includes/XMLParser.h \
		Includes/IDllLoader.h \
		Includes/View.h \
		Includes/Factory.h \
		Includes/Inscription.h \
		Includes/UnixDllLoader.h \
		Includes/IModule.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o Client/main.cpp

Factory.o: Gui/Factory.cpp Includes/Factory.h \
		Includes/View.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Factory.o Gui/Factory.cpp

Home.o: Gui/Home.cpp Includes/View.h \
		Includes/Home.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Home.o Gui/Home.cpp

Inscription.o: Gui/Inscription.cpp Includes/Inscription.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Inscription.o Gui/Inscription.cpp

XMLParser.o: Parser/XMLParser.cpp Includes/XMLParser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o XMLParser.o Parser/XMLParser.cpp

UnixDllLoadder.o: Modules/DllLoader/UnixDllLoadder.cpp Includes/UnixDllLoader.h \
		Includes/IDllLoader.h \
		Includes/IModule.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UnixDllLoadder.o Modules/DllLoader/UnixDllLoadder.cpp

moc_Inscription.o: moc_Inscription.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Inscription.o moc_Inscription.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

