#############################################################################
# Makefile for building: Babel
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  sans_titre.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile sans_titre.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/opt/Qt5.3.2/5.3/gcc/mkspecs/linux-g++ -I. -I/opt/Qt5.3.2/5.3/gcc/include -I/opt/Qt5.3.2/5.3/gcc/include/QtWidgets -I/opt/Qt5.3.2/5.3/gcc/include/QtGui -I/opt/Qt5.3.2/5.3/gcc/include/QtCore -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/Qt5.3.2/5.3/gcc -Wl,-rpath,/opt/Qt5.3.2/5.3/gcc/lib
LIBS          = $(SUBLIBS) -L/opt/Qt5.3.2/5.3/gcc/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Gui/main.cpp \
		Gui/Connection.cpp \
		Gui/Subscribe.cpp \
		Gui/Home.cpp moc_Connection.cpp \
		moc_Subscribe.cpp \
		moc_Home.cpp
OBJECTS       = main.o \
		Connection.o \
		Subscribe.o \
		Home.o \
		moc_Connection.o \
		moc_Subscribe.o \
		moc_Home.o
DIST          = /opt/Qt5.3.2/5.3/gcc/mkspecs/features/spec_pre.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/common/shell-unix.conf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/common/unix.conf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/common/linux.conf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/common/gcc-base.conf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/common/g++-base.conf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/common/g++-unix.conf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/qconfig.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_enginio.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/qt_functions.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/qt_config.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/linux-g++/qmake.conf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/spec_post.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/default_pre.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/resolve_config.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/default_post.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/warn_on.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/qt.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/resources.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/moc.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/unix/opengl.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/uic.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/unix/thread.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/exceptions.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/yacc.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/lex.prf \
		sans_titre.pro Gui/main.cpp \
		Gui/Connection.cpp \
		Gui/Subscribe.cpp \
		Gui/Home.cpp
QMAKE_TARGET  = Babel
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Babel


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_Connection.h ui_Subscribe.h ui_Home.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: sans_titre.pro /opt/Qt5.3.2/5.3/gcc/mkspecs/linux-g++/qmake.conf /opt/Qt5.3.2/5.3/gcc/mkspecs/features/spec_pre.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/common/shell-unix.conf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/common/unix.conf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/common/linux.conf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/common/gcc-base.conf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/common/g++-base.conf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/common/g++-unix.conf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/qconfig.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_enginio.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/qt_functions.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/qt_config.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/linux-g++/qmake.conf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/spec_post.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/default_pre.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/resolve_config.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/default_post.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/warn_on.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/qt.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/resources.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/moc.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/unix/opengl.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/uic.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/unix/thread.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/exceptions.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/yacc.prf \
		/opt/Qt5.3.2/5.3/gcc/mkspecs/features/lex.prf \
		sans_titre.pro \
		/opt/Qt5.3.2/5.3/gcc/lib/libQt5Widgets.prl \
		/opt/Qt5.3.2/5.3/gcc/lib/libQt5Gui.prl \
		/opt/Qt5.3.2/5.3/gcc/lib/libQt5Core.prl
	$(QMAKE) -o Makefile sans_titre.pro
/opt/Qt5.3.2/5.3/gcc/mkspecs/features/spec_pre.prf:
/opt/Qt5.3.2/5.3/gcc/mkspecs/common/shell-unix.conf:
/opt/Qt5.3.2/5.3/gcc/mkspecs/common/unix.conf:
/opt/Qt5.3.2/5.3/gcc/mkspecs/common/linux.conf:
/opt/Qt5.3.2/5.3/gcc/mkspecs/common/gcc-base.conf:
/opt/Qt5.3.2/5.3/gcc/mkspecs/common/gcc-base-unix.conf:
/opt/Qt5.3.2/5.3/gcc/mkspecs/common/g++-base.conf:
/opt/Qt5.3.2/5.3/gcc/mkspecs/common/g++-unix.conf:
/opt/Qt5.3.2/5.3/gcc/mkspecs/qconfig.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_core.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_declarative.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_declarative_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_designer_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_enginio.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_help.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_help_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_network.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_nfc.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_positioning.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_quick_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_script.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_script_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_scripttools.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_serialport.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_webkit.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_websockets.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_x11extras.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/Qt5.3.2/5.3/gcc/mkspecs/features/qt_functions.prf:
/opt/Qt5.3.2/5.3/gcc/mkspecs/features/qt_config.prf:
/opt/Qt5.3.2/5.3/gcc/mkspecs/linux-g++/qmake.conf:
/opt/Qt5.3.2/5.3/gcc/mkspecs/features/spec_post.prf:
/opt/Qt5.3.2/5.3/gcc/mkspecs/features/exclusive_builds.prf:
/opt/Qt5.3.2/5.3/gcc/mkspecs/features/default_pre.prf:
/opt/Qt5.3.2/5.3/gcc/mkspecs/features/resolve_config.prf:
/opt/Qt5.3.2/5.3/gcc/mkspecs/features/default_post.prf:
/opt/Qt5.3.2/5.3/gcc/mkspecs/features/warn_on.prf:
/opt/Qt5.3.2/5.3/gcc/mkspecs/features/qt.prf:
/opt/Qt5.3.2/5.3/gcc/mkspecs/features/resources.prf:
/opt/Qt5.3.2/5.3/gcc/mkspecs/features/moc.prf:
/opt/Qt5.3.2/5.3/gcc/mkspecs/features/unix/opengl.prf:
/opt/Qt5.3.2/5.3/gcc/mkspecs/features/uic.prf:
/opt/Qt5.3.2/5.3/gcc/mkspecs/features/unix/thread.prf:
/opt/Qt5.3.2/5.3/gcc/mkspecs/features/testcase_targets.prf:
/opt/Qt5.3.2/5.3/gcc/mkspecs/features/exceptions.prf:
/opt/Qt5.3.2/5.3/gcc/mkspecs/features/yacc.prf:
/opt/Qt5.3.2/5.3/gcc/mkspecs/features/lex.prf:
sans_titre.pro:
/opt/Qt5.3.2/5.3/gcc/lib/libQt5Widgets.prl:
/opt/Qt5.3.2/5.3/gcc/lib/libQt5Gui.prl:
/opt/Qt5.3.2/5.3/gcc/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile sans_titre.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/Babel1.0.0 || mkdir -p .tmp/Babel1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/Babel1.0.0/ && $(COPY_FILE) --parents Includes/Connection.h Includes/Subscribe.h Includes/Home.h Includes/IGui.h .tmp/Babel1.0.0/ && $(COPY_FILE) --parents Gui/main.cpp Gui/Connection.cpp Gui/Subscribe.cpp Gui/Home.cpp .tmp/Babel1.0.0/ && $(COPY_FILE) --parents Gui/Ui/Connection.ui Gui/Ui/Subscribe.ui Gui/Ui/Home.ui .tmp/Babel1.0.0/ && (cd `dirname .tmp/Babel1.0.0` && $(TAR) Babel1.0.0.tar Babel1.0.0 && $(COMPRESS) Babel1.0.0.tar) && $(MOVE) `dirname .tmp/Babel1.0.0`/Babel1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Babel1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_Connection.cpp moc_Subscribe.cpp moc_Home.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Connection.cpp moc_Subscribe.cpp moc_Home.cpp
moc_Connection.cpp: Includes/IGui.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QMainWindow \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qmainwindow.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qwidget.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qwindowdefs.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qglobal.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qconfig.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qfeatures.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsystemdetection.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qprocessordetection.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qtypeinfo.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qtypetraits.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsysinfo.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qlogging.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qflags.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qbasicatomic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qgenericatomic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_mips.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_x86.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_unix.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qglobalstatic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmutex.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qnumeric.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobjectdefs.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qnamespace.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobject.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstring.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qchar.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qbytearray.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qrefcount.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qarraydata.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstringbuilder.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qlist.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qalgorithms.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qiterator.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcoreevent.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qscopedpointer.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmetatype.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qisenum.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobject_impl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmargins.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpaintdevice.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qrect.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsize.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qpoint.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpalette.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qcolor.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qrgb.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstringlist.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qdatastream.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qiodevice.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qpair.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qregexp.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstringmatcher.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qbrush.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qvector.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qmatrix.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpolygon.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qregion.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qline.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qtransform.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpainterpath.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qimage.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpixmap.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsharedpointer.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qshareddata.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qhash.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qfont.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qfontmetrics.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qfontinfo.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qcursor.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qkeysequence.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qevent.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qvariant.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmap.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qdebug.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qtextstream.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qlocale.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qset.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qurl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qurlquery.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qfile.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qfiledevice.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qvector2d.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qtouchdevice.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qtabwidget.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qicon.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QMessageBox \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qmessagebox.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qdialog.h \
		Includes/Connection.h
	/opt/Qt5.3.2/5.3/gcc/bin/moc $(DEFINES) -I/opt/Qt5.3.2/5.3/gcc/mkspecs/linux-g++ -I/home/napsters/Git/babel -I/opt/Qt5.3.2/5.3/gcc/include -I/opt/Qt5.3.2/5.3/gcc/include/QtWidgets -I/opt/Qt5.3.2/5.3/gcc/include/QtGui -I/opt/Qt5.3.2/5.3/gcc/include/QtCore Includes/Connection.h -o moc_Connection.cpp

moc_Subscribe.cpp: Includes/IGui.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QWidget \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qwidget.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qwindowdefs.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qglobal.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qconfig.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qfeatures.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsystemdetection.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qprocessordetection.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qtypeinfo.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qtypetraits.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsysinfo.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qlogging.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qflags.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qbasicatomic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qgenericatomic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_mips.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_x86.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_unix.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qglobalstatic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmutex.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qnumeric.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobjectdefs.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qnamespace.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobject.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstring.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qchar.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qbytearray.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qrefcount.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qarraydata.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstringbuilder.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qlist.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qalgorithms.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qiterator.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcoreevent.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qscopedpointer.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmetatype.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qisenum.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobject_impl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmargins.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpaintdevice.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qrect.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsize.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qpoint.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpalette.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qcolor.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qrgb.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstringlist.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qdatastream.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qiodevice.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qpair.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qregexp.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstringmatcher.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qbrush.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qvector.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qmatrix.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpolygon.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qregion.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qline.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qtransform.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpainterpath.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qimage.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpixmap.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsharedpointer.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qshareddata.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qhash.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qfont.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qfontmetrics.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qfontinfo.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qcursor.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qkeysequence.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qevent.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qvariant.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmap.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qdebug.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qtextstream.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qlocale.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qset.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qurl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qurlquery.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qfile.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qfiledevice.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qvector2d.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qtouchdevice.h \
		Includes/Subscribe.h
	/opt/Qt5.3.2/5.3/gcc/bin/moc $(DEFINES) -I/opt/Qt5.3.2/5.3/gcc/mkspecs/linux-g++ -I/home/napsters/Git/babel -I/opt/Qt5.3.2/5.3/gcc/include -I/opt/Qt5.3.2/5.3/gcc/include/QtWidgets -I/opt/Qt5.3.2/5.3/gcc/include/QtGui -I/opt/Qt5.3.2/5.3/gcc/include/QtCore Includes/Subscribe.h -o moc_Subscribe.cpp

moc_Home.cpp: /opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QMainWindow \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qmainwindow.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qwidget.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qwindowdefs.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qglobal.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qconfig.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qfeatures.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsystemdetection.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qprocessordetection.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qtypeinfo.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qtypetraits.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsysinfo.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qlogging.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qflags.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qbasicatomic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qgenericatomic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_mips.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_x86.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_unix.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qglobalstatic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmutex.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qnumeric.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobjectdefs.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qnamespace.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobject.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstring.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qchar.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qbytearray.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qrefcount.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qarraydata.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstringbuilder.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qlist.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qalgorithms.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qiterator.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcoreevent.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qscopedpointer.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmetatype.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qisenum.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobject_impl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmargins.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpaintdevice.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qrect.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsize.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qpoint.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpalette.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qcolor.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qrgb.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstringlist.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qdatastream.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qiodevice.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qpair.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qregexp.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstringmatcher.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qbrush.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qvector.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qmatrix.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpolygon.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qregion.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qline.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qtransform.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpainterpath.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qimage.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpixmap.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsharedpointer.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qshareddata.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qhash.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qfont.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qfontmetrics.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qfontinfo.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qcursor.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qkeysequence.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qevent.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qvariant.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmap.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qdebug.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qtextstream.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qlocale.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qset.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qurl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qurlquery.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qfile.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qfiledevice.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qvector2d.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qtouchdevice.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qtabwidget.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qicon.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QHBoxLayout \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qboxlayout.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qlayout.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qlayoutitem.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qgridlayout.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QMessageBox \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qmessagebox.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qdialog.h \
		Includes/Home.h
	/opt/Qt5.3.2/5.3/gcc/bin/moc $(DEFINES) -I/opt/Qt5.3.2/5.3/gcc/mkspecs/linux-g++ -I/home/napsters/Git/babel -I/opt/Qt5.3.2/5.3/gcc/include -I/opt/Qt5.3.2/5.3/gcc/include/QtWidgets -I/opt/Qt5.3.2/5.3/gcc/include/QtGui -I/opt/Qt5.3.2/5.3/gcc/include/QtCore Includes/Home.h -o moc_Home.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_Connection.h ui_Subscribe.h ui_Home.h
compiler_uic_clean:
	-$(DEL_FILE) ui_Connection.h ui_Subscribe.h ui_Home.h
ui_Connection.h: Gui/Ui/Connection.ui
	/opt/Qt5.3.2/5.3/gcc/bin/uic Gui/Ui/Connection.ui -o ui_Connection.h

ui_Subscribe.h: Gui/Ui/Subscribe.ui
	/opt/Qt5.3.2/5.3/gcc/bin/uic Gui/Ui/Subscribe.ui -o ui_Subscribe.h

ui_Home.h: Gui/Ui/Home.ui
	/opt/Qt5.3.2/5.3/gcc/bin/uic Gui/Ui/Home.ui -o ui_Home.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: Gui/main.cpp Includes/IGui.h \
		Includes/Connection.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QMainWindow \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qmainwindow.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qwidget.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qwindowdefs.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qglobal.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qconfig.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qfeatures.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsystemdetection.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qprocessordetection.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qtypeinfo.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qtypetraits.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsysinfo.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qlogging.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qflags.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qbasicatomic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qgenericatomic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_mips.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_x86.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_unix.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qglobalstatic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmutex.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qnumeric.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobjectdefs.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qnamespace.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobject.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstring.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qchar.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qbytearray.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qrefcount.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qarraydata.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstringbuilder.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qlist.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qalgorithms.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qiterator.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcoreevent.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qscopedpointer.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmetatype.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qisenum.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobject_impl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmargins.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpaintdevice.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qrect.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsize.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qpoint.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpalette.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qcolor.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qrgb.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstringlist.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qdatastream.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qiodevice.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qpair.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qregexp.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstringmatcher.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qbrush.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qvector.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qmatrix.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpolygon.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qregion.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qline.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qtransform.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpainterpath.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qimage.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpixmap.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsharedpointer.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qshareddata.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qhash.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qfont.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qfontmetrics.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qfontinfo.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qcursor.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qkeysequence.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qevent.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qvariant.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmap.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qdebug.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qtextstream.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qlocale.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qset.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qurl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qurlquery.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qfile.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qfiledevice.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qvector2d.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qtouchdevice.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qtabwidget.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qicon.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QMessageBox \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qmessagebox.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qdialog.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QApplication \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qapplication.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcoreapplication.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qeventloop.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qdesktopwidget.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qguiapplication.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o Gui/main.cpp

Connection.o: Gui/Connection.cpp Includes/IGui.h \
		Includes/Connection.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QMainWindow \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qmainwindow.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qwidget.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qwindowdefs.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qglobal.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qconfig.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qfeatures.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsystemdetection.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qprocessordetection.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qtypeinfo.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qtypetraits.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsysinfo.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qlogging.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qflags.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qbasicatomic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qgenericatomic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_mips.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_x86.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_unix.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qglobalstatic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmutex.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qnumeric.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobjectdefs.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qnamespace.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobject.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstring.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qchar.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qbytearray.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qrefcount.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qarraydata.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstringbuilder.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qlist.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qalgorithms.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qiterator.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcoreevent.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qscopedpointer.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmetatype.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qisenum.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobject_impl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmargins.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpaintdevice.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qrect.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsize.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qpoint.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpalette.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qcolor.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qrgb.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstringlist.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qdatastream.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qiodevice.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qpair.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qregexp.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstringmatcher.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qbrush.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qvector.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qmatrix.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpolygon.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qregion.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qline.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qtransform.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpainterpath.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qimage.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpixmap.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsharedpointer.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qshareddata.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qhash.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qfont.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qfontmetrics.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qfontinfo.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qcursor.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qkeysequence.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qevent.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qvariant.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmap.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qdebug.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qtextstream.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qlocale.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qset.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qurl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qurlquery.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qfile.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qfiledevice.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qvector2d.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qtouchdevice.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qtabwidget.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qicon.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QMessageBox \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qmessagebox.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qdialog.h \
		Includes/Subscribe.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QWidget \
		Includes/Home.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QHBoxLayout \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qboxlayout.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qlayout.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qlayoutitem.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qgridlayout.h \
		ui_Connection.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/QVariant \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QAction \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qaction.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qactiongroup.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QApplication \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qapplication.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcoreapplication.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qeventloop.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qdesktopwidget.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qguiapplication.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qinputmethod.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QButtonGroup \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qbuttongroup.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QHeaderView \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qheaderview.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qabstractitemview.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qabstractscrollarea.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qframe.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qabstractitemmodel.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qitemselectionmodel.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qabstractitemdelegate.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qstyleoption.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qabstractspinbox.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qvalidator.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qregularexpression.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qslider.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qabstractslider.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qstyle.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qtabbar.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qrubberband.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QLabel \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qlabel.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QLineEdit \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qlineedit.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qtextcursor.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qtextformat.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpen.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qtextoption.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QMenuBar \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qmenubar.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qmenu.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QPushButton \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qpushbutton.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qabstractbutton.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QStatusBar \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qstatusbar.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QToolBar \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qtoolbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Connection.o Gui/Connection.cpp

Subscribe.o: Gui/Subscribe.cpp Includes/Subscribe.h \
		Includes/IGui.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QWidget \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qwidget.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qwindowdefs.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qglobal.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qconfig.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qfeatures.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsystemdetection.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qprocessordetection.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qtypeinfo.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qtypetraits.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsysinfo.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qlogging.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qflags.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qbasicatomic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qgenericatomic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_mips.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_x86.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_unix.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qglobalstatic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmutex.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qnumeric.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobjectdefs.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qnamespace.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobject.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstring.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qchar.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qbytearray.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qrefcount.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qarraydata.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstringbuilder.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qlist.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qalgorithms.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qiterator.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcoreevent.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qscopedpointer.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmetatype.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qisenum.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobject_impl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmargins.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpaintdevice.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qrect.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsize.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qpoint.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpalette.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qcolor.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qrgb.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstringlist.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qdatastream.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qiodevice.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qpair.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qregexp.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstringmatcher.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qbrush.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qvector.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qmatrix.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpolygon.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qregion.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qline.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qtransform.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpainterpath.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qimage.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpixmap.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsharedpointer.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qshareddata.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qhash.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qfont.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qfontmetrics.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qfontinfo.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qcursor.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qkeysequence.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qevent.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qvariant.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmap.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qdebug.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qtextstream.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qlocale.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qset.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qurl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qurlquery.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qfile.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qfiledevice.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qvector2d.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qtouchdevice.h \
		Includes/Connection.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QMainWindow \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qmainwindow.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qtabwidget.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qicon.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QMessageBox \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qmessagebox.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qdialog.h \
		ui_Subscribe.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/QVariant \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QAction \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qaction.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qactiongroup.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QApplication \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qapplication.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcoreapplication.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qeventloop.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qdesktopwidget.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qguiapplication.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qinputmethod.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QButtonGroup \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qbuttongroup.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QHeaderView \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qheaderview.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qabstractitemview.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qabstractscrollarea.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qframe.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qabstractitemmodel.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qitemselectionmodel.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qabstractitemdelegate.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qstyleoption.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qabstractspinbox.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qvalidator.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qregularexpression.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qslider.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qabstractslider.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qstyle.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qtabbar.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qrubberband.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QLabel \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qlabel.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QLineEdit \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qlineedit.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qtextcursor.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qtextformat.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpen.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qtextoption.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QPushButton \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qpushbutton.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qabstractbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Subscribe.o Gui/Subscribe.cpp

Home.o: Gui/Home.cpp Includes/Home.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QMainWindow \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qmainwindow.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qwidget.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qwindowdefs.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qglobal.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qconfig.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qfeatures.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsystemdetection.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qprocessordetection.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qtypeinfo.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qtypetraits.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsysinfo.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qlogging.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qflags.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qbasicatomic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qgenericatomic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_mips.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_x86.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qatomic_unix.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qglobalstatic.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmutex.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qnumeric.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobjectdefs.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qnamespace.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobject.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstring.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qchar.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qbytearray.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qrefcount.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qarraydata.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstringbuilder.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qlist.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qalgorithms.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qiterator.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcoreevent.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qscopedpointer.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmetatype.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qisenum.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qobject_impl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmargins.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpaintdevice.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qrect.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsize.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qpoint.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpalette.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qcolor.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qrgb.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstringlist.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qdatastream.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qiodevice.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qpair.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qregexp.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qstringmatcher.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qbrush.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qvector.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qmatrix.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpolygon.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qregion.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qline.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qtransform.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpainterpath.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qimage.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpixmap.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsharedpointer.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qshareddata.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qhash.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qfont.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qfontmetrics.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qfontinfo.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qcursor.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qkeysequence.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qevent.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qvariant.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qmap.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qdebug.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qtextstream.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qlocale.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qset.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qurl.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qurlquery.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qfile.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qfiledevice.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qvector2d.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qtouchdevice.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qtabwidget.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qicon.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QHBoxLayout \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qboxlayout.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qlayout.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qlayoutitem.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qgridlayout.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QMessageBox \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qmessagebox.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qdialog.h \
		ui_Home.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/QVariant \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QAction \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qaction.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qactiongroup.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QApplication \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qapplication.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qcoreapplication.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qeventloop.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qdesktopwidget.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qguiapplication.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qinputmethod.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QButtonGroup \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qbuttongroup.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QHeaderView \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qheaderview.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qabstractitemview.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qabstractscrollarea.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qframe.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qabstractitemmodel.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qitemselectionmodel.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qabstractitemdelegate.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qstyleoption.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qabstractspinbox.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qvalidator.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtCore/qregularexpression.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qslider.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qabstractslider.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qstyle.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qtabbar.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qrubberband.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QLabel \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qlabel.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QLineEdit \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qlineedit.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qtextcursor.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qtextformat.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qpen.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qtextoption.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QListWidget \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qlistwidget.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qlistview.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QMenuBar \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qmenubar.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qmenu.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QPushButton \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qpushbutton.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qabstractbutton.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QStatusBar \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qstatusbar.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QTextEdit \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/qtextedit.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtGui/qtextdocument.h \
		/opt/Qt5.3.2/5.3/gcc/include/QtWidgets/QWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Home.o Gui/Home.cpp

moc_Connection.o: moc_Connection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Connection.o moc_Connection.cpp

moc_Subscribe.o: moc_Subscribe.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Subscribe.o moc_Subscribe.cpp

moc_Home.o: moc_Home.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Home.o moc_Home.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

