######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 6 20:26:58 2014
######################################################################

QT = xml core gui widgets
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += XMLParser.h
SOURCES += main.cpp XMLParser.cpp
